<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>030-promise的catch和finally方法.html</title>
</head>
<body>
	
</body>
<script type="text/javascript">
	const promise = new Promise((resolve,reject)=>{
		setTimeout(()=>{
			resolve('get data ok!');
			// reject('get data err!');
		},200)
	})

/*
	promise
	.then((data)=>{
		console.log(data);
	},(err)=>{
		console.log(err);
	})
*/
	promise
	.then((data)=>{
		console.log(data);
	})
	.catch((err)=>{// catch 用来专门接收失败的参数
		console.log(err);
	})
	.finally(()=>{// 无论成功还是失败 都会调用finally函数  不接收参数
		console.log('always ok!')
	})
</script>
</html>